import {POLICY} from './html-policy';
import {TERM} from './html-term';

export const JA = {
	UserAdmin: {
		title: '管理者',
		accountManagement: 'アカウント管理:',
		changePassword: 'パスワード変更',
		otherInformation: 'その他の情報:',
		updatePaymentMethod: '支払い方法の更新',
		termsAndConditions: '利用規約',
		privacyPolicy: 'プライバシーポリシー',
		faqs: 'よくある質問',
		logout: 'ログアウト',
		logoutConfirmation: 'ログアウトしますか？',
		settingsButtonText: '設定',
	},
	BottomTab: {
		logoutAlert: 'アカウントがブロックされています！',
		logoutAlertReason: (reasonBlock: string) => `ブロックの理由: ${reasonBlock}`,
	},
	Transactionsrequireconfirmation:{
		title: "取引には確認が必要です",
	},
	ManageUser:{
		title: "ユーザーの管理",
	},
	Home: {
		title: 'ホーム',
		Listofservices: 'サービスの一覧',
		all: 'すべて',
		outstandingservice: '注目のサービス',
		servicesavailable: '利用可能なサービスはありません',
		filterCategory: (text: string) => `${text} サービス`,
		all_service: 'すべてのサービス',
	},
	Notification: {
		title: '通知',
		notifiavailable: '利用可能な通知はありません',
		delete_success: '削除成功！',
	},
	Order: {
		title: '注文',
		all: 'すべて',
		pending: '保留中',
		inprocess: '進行中',
		completed: '完了',
		canceled: 'キャンセル',
	},
	OrderAll: {
		no_order: '注文はありません！',
	},
	User: {
		title: 'プロフィール',
		activityStatusText: 'アクティビティステータス',
		updateInfoButtonText: '情報の更新',
		addressButtonText: '住所',
		changePasswordButtonText: 'パスワード変更',
		feeServiceText: 'サービス料金: ',
		blockedUsersButtonText: 'ブロックされたユーザーリスト',
		otherInfoText: 'その他の情報',
		termsButtonText: '利用規約',
		privacyPolicyButtonText: 'プライバシーポリシー',
		faqsButtonText: 'よくある質問',
		settingsButtonText: '設定',
		logoutButtonText: 'ログアウト',
		logoutConfirmationMessage: 'ログアウトしますか？',
		unpaid: '未払い',
		paid: '支払済み',
		wait: '承認待ち',
		ACCOUNT_MANAGEMENT: 'アカウント管理',
		SERVICE: 'サービス',
	},
	Search: {
		title: '検索',
		entersearch: '検索情報を入力',
		sort: '並び替え',
		filters: 'フィルター',
		servicesavailable: '利用可能なサービスはありません',
		sort1: '評価が高い順',
		sort2: '評価が低い順',
		all: 'すべて',
	},
	DetailService: {
		title: 'サービスの詳細',
		descriptionservicesL: 'サービスの説明',
		description: '評価内容',
		suggestions: 'おすすめ',
		infomationprovider: 'プロバイダー情報',
		booking: '予約',
		evulate: '評価',
		allevulate: 'すべての評価を見る',
		noevulate: '評価はありません',
		servicerNotActive: 'このプロバイダーは現在アクティブではありません！',
		servicerBlocked: 'このユーザーにブロックされています！',
		shareService: 'サービスを共有',
		shareMessage: (service: string, name: string, link: string) =>
			`${name}によって共有された${service}サービスを注文するためにリンクをクリックしてください。リンク: ${link}`,
		shareError: 'エラーが発生しました！',
	},
	Booking: {
		title: '予約',
		namecustomer: 'お客様の名前',
		phonecustomer: '電話番号',
		addresscustomer: '住所',
		localaddress: '現在の位置を使用',
		chooseaddress: '住所を選択',
		datebooking: '予約日',
		timebooking: '予約時間',
		desprolem: '問題の説明',
		image: '画像',
		choosebooking: '予約日を選択',
		booking: '予約',
		alertMessage: '情報をよく確認しましたか？',
		booking_success: (text: string) => `注文が正常に作成されました！ ${text}`,
	},
	InfoServicer: {
		title: '詳細情報',
		all: '提供されているすべてのサービス',
		noservicer: '利用可能なサービスはありません',
		allevulate: 'すべての評価',
		noevulate: '評価はありません',
	},
	AllReview: {
		title: 'すべての評価',
	},
	NotificationDetail: {
		title: '通知の詳細',
	},
	ChangePassword: {
		title: 'パスワード変更',
		enterpass: '現在のパスワードを入力',
		enterpassnew: '新しいパスワードを入力',
		enterpassnew1: '新しいパスワードを再入力',
		currentPasswordIncorrect: '現在のパスワードが間違っています！',
		passwordMismatch: 'パスワードが一致しません！',
		confirmChangePassword: 'パスワードを変更しますか？',
		changePasswordSuccess: 'パスワードが正常に変更されました！',
		changePasswordFailure: 'パスワードの変更に失敗しました',
	},
	Setting: {
		title: '設定',
		listLanguage: ['ベトナム語', '英語', '中国語', '日本語', '韓国語'],
		Language: '言語',
	},
	TermsAndConditions: {
		title: 'プライバシーポリシー',
		HTML: TERM.JA,
	},
	UpdateInformation: {
		title: '情報の更新',
		fullname: 'フルネーム',
		phonenumber: '電話番号',
		addresss: '住所',
		save: '保存',
		showmessagename: '名前が不足しています',
		missingPhoneNumber: '電話番号が不足しています',
		saveSuccess: '保存に成功しました',
		saveFailure: '情報の保存に失敗しました',
	},
	ListAddress: {
		title: '住所帳',
		addaddress: '住所を追加',
		noaddress: '住所情報はありません',
		name: '名前: ',
		phone: '電話番号: ',
		address: '住所: ',
		deleteConfirm: '削除しますか？',
	},
	DetailOrder: {
		title: '注文の詳細',
		status: 'ステータス',
		description: '説明',
		timebooking: '予約時間',
		appointmentschedule: '予約スケジュール',
		address: '住所',
		reason: '理由',
		result: '結果',
		cancel: 'キャンセル',
		comform: '確認',
		complete: '完了',
		report: '報告',
		evulate: '評価',
		Provideslevelresults: '提供された結果',
		des: '問題が発生した場合に比較するために結果の画像をアップロードしてください',
		des1: 'サービスが説明と一致しない',
		other: 'その他',
		cancelorder: '注文のキャンセル',
		enterdes: '理由を入力してください',
		enterdo: '理由を入力してください',
		confirmSuccess: '確認に成功しました！',
		orderCancelled: '注文がキャンセルされました！',
		cancelSuccess: '注文のキャンセルに成功しました！',
		cannotCancel: 'キャンセルできません！',
		orderInProcess: '注文は確認され、処理中です！',
		completionSuccess: '注文が完了しました！',
		reportPrompt: '報告',
		reportDescription1: 'サービスが説明と一致しない',
		reportOther: 'その他',
		reportEnterDescription: '理由を入力してください',
		reportCancel: 'キャンセル',
		reportSubmit: '完了',
	},
	AddService: {
		title: 'サービスを追加',
		category: 'カテゴリ',
		selectCategory: 'カテゴリを選択',
		serviceName: 'サービス名',
		image: '画像',
		uploadImage: '画像をアップロード',
		description: '説明',
		addService: '追加',
		editService: '編集',
		confirmCheckInfo: '情報をよく確認しましたか？',
		successMessage: 'サービスが正常に追加されました',
		editMessage: 'サービスが正常に編集されました！',
	},
	AcceptServicer: {
		title: 'アカウントの承認',
		date: (text: string) => `登録日: ${text}`,
	},
	Payment: {
		title: '支払い',
		feeservicer: 'サービス料金',
		payfees: '50,000 VND/月',
		bank: '銀行',
		bankname: 'Techcombank',
		numberaccount: '口座番号',
		nameaccount: 'カード名義',
		descriptsion: '内容',
	},
	EvaluateService: {
		title: 'サービスの評価',
		description: '評価の内容',
		enterdescription: '評価を入力してください',
		image: '画像',
		evulate: '評価',
		successMessage: '評価が成功しました',
	},
	PrivacyPolicy: {
		title: '利用規約',
		HTML: POLICY.JA,
	},
	FAQ: {
		title: 'よくある質問',
		content: '以下は、モバイルアプリ「メンテナンスおよび修理サービス」のいくつかのよくある質問（FAQs）の例です',
		question: '質問 ',
		answer: '- 回答: ',
	},
	HomeServicer: {
		title: '注文',
		pending: '承認待ち',
		inprocess: '進行中',
		completed: '完了',
		canceled: 'キャンセル済み',
	},
	Listblock: {
		title: 'ブロックリスト',
		block: 'ブロック',
		enterPhoneNumber: '電話番号を入力してください。',
		invalidPhoneNumber: '無効な電話番号です。',
		blockSuccess: '電話番号を正常にブロックしました！',
		confirmDelete: '削除しますか？',
		deleteSuccess: '削除に成功しました！',
	},
	HomeAdmin: {
		title: '家',
		AccountWitingForApproval: 'アカウントは承認待ちです',
		AccountUserManager: 'ユーザーアカウントの管理',
		AccountProviderManager: 'サービスプロバイダーのアカウント管理',
		BROWSEWAYSTODEPOSIT:'入金方法を参照する',
	},
	OrderServicer: {
		title: '私のサービス',
		servicesavailable: 'サービスはありません',
		confirmDelete: '削除しますか？',
		deleteSuccess: 'サービスが正常に削除されました！',
	},
	StatusOrder: {
		OrderPending: '注文保留中',
		OrderCanceled: '注文キャンセル済み',
		OrderInProcess: '注文処理中',
		OrderCompleted: '注文完了済み',
	},
	AddPayment:{
		title: "THÊM PHƯƠNG THỨC THANH TOÁN",
		
	}
};
