import {POLICY} from './html-policy';
import {TERM} from './html-term';

export const KO = {
	UserAdmin: {
		title: '어드민',
		accountManagement: '계정 관리:',
		changePassword: '비밀번호 변경',
		otherInformation: '기타 정보:',
		updatePaymentMethod: '결제 방법 업데이트',
		termsAndConditions: '약관 및 조건',
		privacyPolicy: '개인정보 처리방침',
		faqs: '자주 묻는 질문',
		logout: '로그아웃',
		logoutConfirmation: '로그아웃하시겠습니까?',
		settingsButtonText: '환경',
	},
	Transactionsrequireconfirmation:{
		title: "거래확인이 필요함",
	},
	ManageUser:{
		title: "사용자 관리",
	},
	HomeAdmin: {
		title: '집',
		AccountWitingForApproval: '승인 대기 중인 계정',
		AccountUserManager: '사용자 계정 관리',
		AccountProviderManager: '서비스 제공업체 계정 관리',
		BROWSEWAYSTODEPOSIT:'입금 방법 찾아보기',
	},
	BottomTab: {
		logoutAlert: '계정이 차단되었습니다!',
		logoutAlertReason: (reasonBlock: string) => `차단된 이유: ${reasonBlock}`,
	},
	Home: {
		title: '홈',
		Listofservices: '서비스 목록',
		all: '모두',
		outstandingservice: '뛰어난 서비스',
		servicesavailable: '이용 가능한 서비스 없음',
		filterCategory: (text: string) => `${text} 서비스`,
		all_service: '모든 서비스',
	},
	Notification: {
		title: '알림',
		notifiavailable: '알림 없음',
		delete_success: '삭제 성공!',
	},
	Order: {
		title: '주문',
		all: '모두',
		pending: '대기 중',
		inprocess: '진행 중',
		completed: '완료됨',
		canceled: '취소됨',
	},
	OrderAll: {
		no_order: '주문 없음!',
	},
	User: {
		title: '사용자 프로필',
		activityStatusText: '활동 상태',
		updateInfoButtonText: '정보 업데이트',
		addressButtonText: '주소',
		changePasswordButtonText: '비밀번호 변경',
		feeServiceText: '서비스 요금: ',
		blockedUsersButtonText: '차단된 사용자 목록',
		otherInfoText: '기타 정보',
		termsButtonText: '약관',
		privacyPolicyButtonText: '개인정보 처리방침',
		faqsButtonText: '자주 묻는 질문',
		settingsButtonText: '설정',
		logoutButtonText: '로그아웃',
		logoutConfirmationMessage: '로그아웃하시겠습니까?',
		unpaid: '미지불',
		paid: '지불됨',
		wait: '승인 대기 중',
		ACCOUNT_MANAGEMENT: '계정 관리',
		SERVICE: '서비스',
	},
	Search: {
		title: '검색',
		entersearch: '검색 정보 입력',
		sort: '정렬',
		filters: '필터',
		servicesavailable: '이용 가능한 서비스 없음',
		sort1: '평가 오름차순',
		sort2: '평가 내림차순',
		all: '모두',
	},
	DetailService: {
		title: '서비스 상세 정보',
		descriptionservicesL: '서비스 설명',
		description: '평가 내용',
		suggestions: '추천 사항',
		infomationprovider: '제공자 정보',
		booking: '예약',
		evulate: '평가',
		allevulate: '모든 평가 보기',
		noevulate: '평가 없음',
		servicerNotActive: '이 제공자는 현재 활동 중이 아닙니다!',
		servicerBlocked: '이 사용자에게 차단당했습니다!',
		shareService: '서비스 공유',
		shareMessage: (service: string, name: string, link: string) =>
			`${service} 서비스를 주문하려면 링크를 클릭하세요. ${name} 님이 공유함. 링크: ${link}`,
		shareError: '오류가 발생했습니다!',
	},
	Booking: {
		title: '예약',
		namecustomer: '고객 이름',
		phonecustomer: '전화번호',
		addresscustomer: '주소',
		localaddress: '현재 위치 사용',
		chooseaddress: '주소 선택',
		datebooking: '예약 날짜',
		timebooking: '예약 시간',
		desprolem: '문제 설명',
		image: '이미지',
		choosebooking: '예약 날짜 선택',
		booking: '예약',
		alertMessage: '정보를 충분히 확인하셨나요?',
		booking_success: (text: string) => `주문이 성공적으로 생성되었습니다! ${text}`,
	},
	InfoServicer: {
		title: '상세 정보',
		all: '제공되는 모든 서비스',
		noservicer: '서비스 없음',
		allevulate: '모든 평가',
		noevulate: '평가 없음',
	},
	AllReview: {
		title: '모든 평가',
	},
	NotificationDetail: {
		title: '알림 상세 정보',
	},
	ChangePassword: {
		title: '비밀번호 변경',
		enterpass: '현재 비밀번호 입력',
		enterpassnew: '새 비밀번호 입력',
		enterpassnew1: '새 비밀번호 다시 입력',
		currentPasswordIncorrect: '현재 비밀번호가 일치하지 않습니다!',
		passwordMismatch: '비밀번호가 일치하지 않습니다!',
		confirmChangePassword: '비밀번호를 변경하시겠습니까?',
		changePasswordSuccess: '비밀번호가 성공적으로 변경되었습니다!',
		changePasswordFailure: '비밀번호 변경에 실패했습니다',
	},
	Setting: {
		title: '설정',
		listLanguage: ['베트남어', '영어', '중국어', '일본어', '한국어'],
		Language: '언어',
	},
	TermsAndConditions: {
		title: '개인 정보 정책',
		HTML: TERM.KO,
	},
	UpdateInformation: {
		title: '정보 업데이트',
		fullname: '이름',
		phonenumber: '전화번호',
		addresss: '주소',
		save: '저장',
		showmessagename: '이름이 누락되었습니다',
		missingPhoneNumber: '전화번호가 누락되었습니다',
		saveSuccess: '성공적으로 저장되었습니다',
		saveFailure: '정보 저장 실패',
	},
	ListAddress: {
		title: '주소록',
		addaddress: '주소 추가',
		noaddress: '주소 정보 없음',
		name: '이름: ',
		phone: '전화번호: ',
		address: '주소: ',
		deleteConfirm: '삭제하시겠습니까?',
	},
	DetailOrder: {
		title: '주문 세부 정보',
		status: '상태',
		description: '설명',
		timebooking: '예약 시간',
		appointmentschedule: '예약 일정',
		address: '주소',
		reason: '이유',
		result: '결과',
		cancel: '취소',
		comform: '확인',
		complete: '완료',
		report: '보고서',
		evulate: '평가',
		Provideslevelresults: '결과 제공',
		des: '문제 발생 시 결과를 대조하기 위해 결과 이미지를 업로드하세요',
		des1: '서비스가 설명과 다름',
		other: '기타',
		cancelorder: '주문 취소',
		enterdes: '이유 입력',
		enterdo: '이유를 입력하세요',
		confirmSuccess: '성공적으로 확인되었습니다!',
		orderCancelled: '주문이 취소되었습니다!',
		cancelSuccess: '주문이 성공적으로 취소되었습니다!',
		cannotCancel: '취소할 수 없습니다!',
		orderInProcess: '주문이 확인되었으며 처리 중입니다!',
		completionSuccess: '주문이 완료되었습니다!',
		reportPrompt: '보고',
		reportDescription1: '서비스가 설명과 다름',
		reportOther: '기타',
		reportEnterDescription: '이유 입력',
		reportCancel: '취소',
		reportSubmit: '완료',
	},
	AddService: {
		title: '서비스 추가',
		category: '서비스 종류',
		selectCategory: '서비스 종류 선택',
		serviceName: '서비스 이름',
		image: '이미지',
		uploadImage: '이미지 업로드',
		description: '설명',
		addService: '추가',
		editService: '수정',
		confirmCheckInfo: '정보를 정확히 확인하셨나요?',
		successMessage: '서비스가 성공적으로 추가되었습니다',
		editMessage: '서비스가 성공적으로 수정되었습니다!',
	},
	AcceptServicer: {
		title: '계정 승인',
		date: (text: string) => `가입일: ${text}`,
	},
	Payment: {
		title: '결제',
		feeservicer: '서비스 수수료',
		payfees: '50,000 VND/월',
		bank: '은행',
		bankname: '택컴뱅크',
		numberaccount: '계좌 번호',
		nameaccount: '카드 소유자 이름',
		descriptsion: '내용',
	},
	EvaluateService: {
		title: '서비스 평가',
		description: '평가 내용',
		enterdescription: '평가를 입력하세요',
		image: '이미지',
		evulate: '평가',
		successMessage: '평가가 성공적으로 완료되었습니다',
	},
	PrivacyPolicy: {
		title: '이용 약관',
		HTML: POLICY.KO,
	},
	FAQ: {
		title: '자주 묻는 질문',
		content: '여기는 모바일 애플리케이션 유지보수 및 수리 서비스에 대한 일부 자주 묻는 질문(FAQ)의 예시입니다',
		question: '질문 ',
		answer: '- 대답: ',
	},
	HomeServicer: {
		title: '주문',
		pending: '승인 대기 중',
		inprocess: '진행 중',
		completed: '완료됨',
		canceled: '취소됨',
	},
	Listblock: {
		title: '차단 목록',
		block: '차단',
		enterPhoneNumber: '전화번호를 입력하세요.',
		invalidPhoneNumber: '유효하지 않은 전화번호입니다.',
		blockSuccess: '전화번호 차단 성공!',
		confirmDelete: '정말 삭제하시겠습니까?',
		deleteSuccess: '삭제 성공!',
	},
	OrderServicer: {
		title: '내 서비스',
		servicesavailable: '사용 가능한 서비스가 없습니다',
		confirmDelete: '정말 삭제하시겠습니까?',
		deleteSuccess: '서비스 삭제 성공!',
	},
	StatusOrder: {
		OrderPending: '주문 대기 중',
		OrderCanceled: '주문 취소됨',
		OrderInProcess: '주문 처리 중',
		OrderCompleted: '주문 완료됨',
	},
	AddPayment:{
		title: "THÊM PHƯƠNG THỨC THANH TOÁN",
		
	}
};
