import {POLICY} from './html-policy';
import {TERM} from './html-term';

export const VI = {
	UserAdmin: {
		title: 'ADMIN',
		accountManagement: 'QUẢN LÝ TÀI KHOẢN:',
		changePassword: 'Đổi mật khẩu',
		otherInformation: 'THÔNG TIN KHÁC:',
		updatePaymentMethod: 'Cập nhật phương thức thanh toán',
		termsAndConditions: 'Quy định và điều khoản',
		privacyPolicy: 'Chính sách quyền riêng tư',
		faqs: 'FAQs',
		logout: 'Đăng xuất',
		logoutConfirmation: 'Bạn chắc chắn muốn đăng xuất?',
		settingsButtonText: 'Cài Đặt',
	},
	BottomTab: {
		logoutAlert: 'Tài khoản của bạn đã bị chặn!',
		logoutAlertReason: (reasonBlock: string) => `Lí do ${reasonBlock}`,
	},
	Transactionsrequireconfirmation: {
		title: 'Giao Dịch Yêu Cầu Xác Nhận',
	},
	ManageUser: {
		title: 'Tài Khoản Người Dùng',
	},
	Home: {
		title: 'TRANG CHỦ',
		Listofservices: 'Danh mục dịch vụ',
		all: 'Tất cả',
		outstandingservice: 'Dịch vụ nổi bật',
		servicesavailable: 'Không có dịch vụ nào',
		filterCategory: (text: string) => `Dịch Vụ ${text}`,
		all_service: 'Tất cả dịch vụ',
	},
	Notification: {
		title: 'THÔNG BÁO',
		notifiavailable: 'Không có thông báo nào',
		delete_success: 'Xoá thành công!',
	},
	Order: {
		title: 'ĐƠN ĐẶT HÀNG',
		all: 'Tất cả',
		pending: 'Đang chờ',
		inprocess: 'Tiến hành',
		completed: 'Hoàn thành',
		canceled: 'Hủy',
	},
	OrderAll: {
		no_order: 'Không có đơn đặt hàng!',
	},
	User: {
		title: 'HỒ SƠ',
		activityStatusText: 'TRẠNG THÁI HOẠT ĐỘNG',
		updateInfoButtonText: 'Cập nhật thông tin',
		addressButtonText: 'Địa chỉ',
		changePasswordButtonText: 'Đổi mật khẩu',
		feeServiceText: 'Phí dịch vụ: ',
		blockedUsersButtonText: 'Danh sách người dùng bị chặn',
		otherInfoText: 'THÔNG TIN KHÁC',
		termsButtonText: 'Quy định điều khoản',
		privacyPolicyButtonText: 'Chính sách quyền riêng tư',
		faqsButtonText: 'FAQs',
		settingsButtonText: 'Cài đặt',
		logoutButtonText: 'Đăng xuất',
		logoutConfirmationMessage: 'Bạn chắc chắn muốn đăng xuất?',
		unpaid: 'Chưa thanh toán',
		paid: 'Đã thanh toán',
		wait: 'Chờ xét duyệt',
		ACCOUNT_MANAGEMENT: 'QUẢN LÝ TÀI KHOẢN',
		SERVICE: 'DỊCH VỤ',
	},
	Search: {
		title: 'TÌM KIẾM',
		entersearch: 'Nhập thông tin tìm kiếm',
		sort: 'Sắp xếp',
		filters: 'Lọc',
		servicesavailable: 'Không có dịch vụ nào',
		sort1: 'Đánh giá tăng dần',
		sort2: 'Đánh giá giảm dần',
		all: 'Tất cả',
	},
	DetailService: {
		title: 'CHI TIẾT DỊCH VỤ',
		descriptionservices: 'Mô tả dịch vụ',
		description: 'Nội dung đánh giá',
		suggestions: 'Gợi ý cho bạn',
		infomationprovider: 'Thông tin thợ',
		booking: 'Đặt lịch',
		evulate: 'Đánh giá',
		allevulate: 'Xem tất cả đánh giá',
		noevulate: 'Không có đánh giá nào',
		servicerNotActive: 'Thợ này hiện không hoạt động!',
		servicerBlocked: 'Bạn đã bị người dùng này chặn!',
		shareService: 'Chia sẻ dịch vụ',
		shareMessage: (service: string, name: string, link: string) =>
			`Hãy nhấn vào link để đặt hàng dịch vụ ${service}. Được chia sẻ bởi ${name}. Liên kết ${link}`,
		shareError: 'Có lỗi sảy ra!',
	},
	Booking: {
		title: 'ĐẶT LỊCH',
		namecustomer: 'TÊN KHÁCH HÀNG',
		phonecustomer: 'SỐ ĐIỆN THOẠI',
		addresscustomer: 'ĐỊA CHỈ',
		localaddress: 'Sử dụng vị trí hiện tại',
		chooseaddress: 'Chọn địa chỉ',
		datebooking: 'NGÀY ĐẶT LỊCH',
		timebooking: 'GIỜ ĐẶT LỊCH',
		desprolem: 'MÔ TẢ VẤN ĐỀ',
		image: 'CÁC HÌNH ẢNH',
		choosebooking: 'CHỌN NGÀY ĐẶT LỊCH',
		booking: 'ĐẶT LỊCH',
		alertMessage: 'Bạn đã kiểm tra kĩ thông tin?',
		booking_success: (text: string) => `Tạo đơn đặt hàng thành công! ${text}`,
	},
	InfoServicer: {
		title: 'THÔNG TIN CHI TIẾT',
		all: 'TẤT CẢ DỊCH VỤ CUNG CẤP',
		noservicer: 'Không có dịch vụ nào',
		allevulate: 'TẤT CẢ ĐÁNH GIÁ',
		noevulate: 'Không có đánh giá nào',
	},
	AllReview: {
		title: 'TẤT CẢ ĐÁNH GIÁ',
	},
	NotificationDetail: {
		title: 'Chi tiết thông báo',
	},
	ChangePassword: {
		title: 'ĐỔI MẬT KHẨU',
		enterpass: 'NHẬP MẬT KHẨU HIỆN TẠI',
		enterpassnew: 'NHẬP MẬT KHẨU MỚI',
		enterpassnew1: 'NHẬP LẠI MẬT KHẨU MỚI',
		currentPasswordIncorrect: 'Sai mật khẩu hiện tại!',
		passwordMismatch: 'Sai mật khẩu xác nhận!',
		confirmChangePassword: 'Bạn chắc chắn muốn đổi mật khẩu?',
		changePasswordSuccess: 'Đổi mật khẩu thành công!',
		changePasswordFailure: 'Đổi mật khẩu thất bại',
	},
	Setting: {
		title: 'CÀI ĐẶT',
		listLanguage: ['Việt Nam', 'Tiếng Anh', 'Tiếng Trung', 'Tiếng Nhật', 'Tiếng Hàn'],
		Language: 'Ngôn ngữ',
	},
	TermsAndConditions: {
		title: 'CHÍNH SÁCH QUYỀN RIÊNG TƯ',
		HTML: TERM.VI,
	},
	UpdateInformation: {
		title: 'CẬP NHẬP THÔNG TIN',
		fullname: 'HỌ VÀ TÊN',
		phonenumber: 'SỐ ĐIỆN THOẠI',
		addresss: 'Địa chỉ',
		save: 'LƯU',
		showmessagename: 'Thiếu tên',
		missingPhoneNumber: 'Thiếu số điện thoại',
		saveSuccess: 'Đã lưu thành công',
		saveFailure: 'Lưu thông tin thất bại',
	},
	ListAddress: {
		title: 'SỔ ĐỊA CHỈ',
		addaddress: 'Thêm địa chỉ',
		noaddress: 'Không có thông tin địa chỉ',
		name: 'Họ tên: ',
		phone: 'Số điện thoại: ',
		address: 'Địa chỉ: ',
		deleteConfirm: 'Bạn có muốn xoá không ?',
	},
	DetailOrder: {
		title: 'CHI TIẾT ĐƠN HÀNG',
		status: 'Trạng thái',
		description: 'Mô tả',
		timebooking: 'Thời gian đặt lịch',
		appointmentschedule: 'Lịch hẹn',
		address: 'Địa chỉ',
		reason: 'Lý do',
		result: 'Kết quả',
		cancel: 'Hủy',
		comform: 'Xác Nhận',
		complete: 'Hoàn thành',
		report: 'Báo cáo',
		evulate: 'Đánh giá',
		Provideslevelresults: 'Cung cấp kết quả',
		des: 'Vui lòng tải lên hình ảnh kết quả để đối chiếu khi có vấn đề phát sinh',
		des1: 'Dịch vụ không đúng mô tả',
		other: 'Khác',
		cancelorder: 'HUỶ ĐƠN HÀNG',
		enterdes: 'NHẬP LÝ DO',
		enterdo: 'Hãy nhập lý do',
		confirmSuccess: 'Xác nhận thành công!',
		orderCancelled: 'Đơn hàng đã bị huỷ!',
		cancelSuccess: 'Huỷ đơn hàng thành công!',
		cannotCancel: 'Không thể huỷ!',
		orderInProcess: 'Đơn hàng đã được xác nhận và đang trong quá trình xử lý!',
		completionSuccess: 'Hoàn thành đơn hàng!',
		reportPrompt: 'Báo cáo',
		reportDescription1: 'Dịch vụ không đúng mô tả',
		reportOther: 'Khác',
		reportEnterDescription: 'Nhập lý do',
		reportCancel: 'Hủy',
		reportSubmit: 'Hoàn thành',
	},
	AddService: {
		title: 'THÊM DỊCH VỤ',
		category: 'LOẠI DỊCH VỤ',
		selectCategory: 'Chọn loại dịch vụ',
		serviceName: 'TÊN DỊCH VỤ',
		image: 'HÌNH ẢNH',
		uploadImage: 'Tải ảnh lên',
		description: 'MÔ TẢ',
		addService: 'THÊM',
		editService: 'SỬA',
		confirmCheckInfo: 'Bạn chắc chắn đã kiểm tra kĩ thông tin?',
		successMessage: 'Thêm dịch vụ thành công',
		editMessage: 'Sửa dịch vụ thành công!',
	},
	AcceptServicer: {
		title: 'XÉT DUYỆT TÀI KHOẢN',
		date: (text: string) => `Ngày đăng ký: ${text}`,
	},
	Payment: {
		title: 'THANH TOÁN',
		feeservicer: 'Phí dịch vụ',
		payfees: '50.000 VND/tháng',
		bank: 'Ngân hàng',
		bankname: 'techcombank',
		numberaccount: 'Số tài khoản',
		nameaccount: 'Tên chủ thẻ',
		descriptsion: 'Nội dung',
	},
	EvaluateService: {
		title: 'ĐÁNH GIÁ DỊCH VỤ',
		description: 'Nội dung đánh giá',
		enterdescription: 'Hãy nhập đánh giá',
		image: 'Hình ảnh',
		evulate: 'Đánh giá',
		successMessage: 'Đánh giá thành công',
	},
	PrivacyPolicy: {
		title: 'QUY ĐỊNH ĐIỀU KHOẢN',
		HTML: POLICY.VI,
	},
	FAQ: {
		title: 'CÁC CÂU HỎI THƯỜNG GẶP',
		content: 'Dưới đây là một ví dụ về một số câu hỏi thường gặp (FAQs) cho ứng dụng di động Maintenance and Repair Services',
		question: 'Câu hỏi ',
		answer: '- Trả lời: ',
	},
	HomeServicer: {
		title: 'ĐƠN HÀNG',
		pending: 'Chờ xác nhận',
		inprocess: 'Tiến hành',
		completed: 'Hoàn thành',
		canceled: 'Đã hủy',
	},
	HomeAdmin: {
		title: 'TRANG CHỦ',
		AccountWitingForApproval: 'TÀI KHOẢN CHỜ XÉT DUYỆT',
		AccountUserManager: 'QUẢN LÝ TÀI KHOẢN NGƯỜI DÙNG',
		AccountProviderManager: 'QUẢN LÝ TÀI KHOẢN NGƯỜI CUNG\nCẤP DỊCH VỤ',
		BROWSEWAYSTODEPOSIT: 'DUYỆT CÁC GIAO DỊCH NẠP TIỀN',
	},
	Listblock: {
		title: 'DANH SÁCH CHẶN',
		block: 'chặn',
		enterPhoneNumber: 'Vui lòng nhập số điện thoại.',
		invalidPhoneNumber: 'Số điện thoại không hợp lệ.',
		blockSuccess: 'Block số điện thoại thành công!',
		confirmDelete: 'Bạn chắc chắn muốn xoá?',
		deleteSuccess: 'Xoá thành công!',
	},
	OrderServicer: {
		title: 'DỊCH VỤ CỦA TÔI',
		servicesavailable: 'Bạn không có dịch vụ nào',
		confirmDelete: 'Bạn chắc chắn muốn xoá?',
		deleteSuccess: 'Xoá dịch vụ thành công!',
	},
	StatusOrder: {
		OrderPending: 'ĐANG CHỜ',
		OrderCanceled: 'ĐÃ HUỶ',
		OrderInProcess: 'ĐANG TIẾN HÀNG',
		OrderCompleted: 'HOÀN THÀNH',
	},
	AddPayment: {
		title: 'THÊM PHƯƠNG THỨC THANH TOÁN',
	},
};
