import {POLICY} from './html-policy';
import {TERM} from './html-term';

export const ZH = {
	UserAdmin: {
		title: '管理员',
		accountManagement: '帐户管理:',
		changePassword: '修改密码',
		otherInformation: '其他信息:',
		updatePaymentMethod: '更新付款方式',
		termsAndConditions: '条款和条件',
		privacyPolicy: '隐私政策',
		faqs: '常见问题',
		logout: '注销',
		logoutConfirmation: '确定要注销吗？',
		settingsButtonText: '環境'
	},
	Transactionsrequireconfirmation:{
		title: "交易需要确认",
	},
	ManageUser:{
		title: "管理用户",
	},
	HomeAdmin: {
		title: '家',
		AccountWitingForApproval: '账户待批准',
		AccountUserManager: '管理用户帐户',
		AccountProviderManager: '服务提供商帐户管理',
		BROWSEWAYSTODEPOSIT:'浏览存款方式',
	},
	BottomTab: {
		logoutAlert: '您的帐户已被封锁！',
		logoutAlertReason: (reasonBlock: string) => `封锁原因 ${reasonBlock}`,
	},
	Home: {
		title: '主页',
		Listofservices: '服务目录',
		all: '全部',
		outstandingservice: '优秀服务',
		servicesavailable: '没有可用的服务',
		filterCategory: (text: string) => `服务 ${text}`,
		all_service: '所有服务',
	},
	Notification: {
		title: '通知',
		notifiavailable: '没有通知',
		delete_success: '删除成功！',
	},
	Order: {
		title: '订单',
		all: '全部',
		pending: '待处理',
		inprocess: '进行中',
		completed: '已完成',
		canceled: '已取消',
	},
	OrderAll: {
		no_order: '没有订单！',
	},
	User: {
		title: '用户档案',
		activityStatusText: '活动状态',
		updateInfoButtonText: '更新信息',
		addressButtonText: '地址',
		changePasswordButtonText: '修改密码',
		feeServiceText: '服务费: ',
		blockedUsersButtonText: '被封锁的用户列表',
		otherInfoText: '其他信息',
		termsButtonText: '条款',
		privacyPolicyButtonText: '隐私政策',
		faqsButtonText: '常见问题',
		settingsButtonText: '设置',
		logoutButtonText: '注销',
		logoutConfirmationMessage: '确定要注销吗？',
		unpaid: '未支付',
		paid: '已支付',
		wait: '等待批准',
		ACCOUNT_MANAGEMENT: '帐户管理',
		SERVICE: '服务',
	},
	Search: {
		title: '搜索',
		entersearch: '输入搜索信息',
		sort: '排序',
		filters: '过滤器',
		servicesavailable: '没有可用的服务',
		sort1: '评价升序',
		sort2: '评价降序',
		all: '全部',
	},
	DetailService: {
		title: '服务详情',
		descriptionservicesL: '服务描述',
		description: '评价内容',
		suggestions: '为您推荐',
		infomationprovider: '服务提供者信息',
		booking: '预订',
		evulate: '评价',
		allevulate: '查看所有评价',
		noevulate: '没有评价',
		servicerNotActive: '此服务提供者当前不活动！',
		servicerBlocked: '您已被此用户封锁！',
		shareService: '分享服务',
		shareMessage: (service: string, name: string, link: string) => `点击链接预订${service}服务。由${name}分享。链接 ${link}`,
		shareError: '出现错误！',
	},
	Booking: {
		title: '预订',
		namecustomer: '顾客姓名',
		phonecustomer: '联系电话',
		addresscustomer: '地址',
		localaddress: '使用当前位置',
		chooseaddress: '选择地址',
		datebooking: '预订日期',
		timebooking: '预订时间',
		desprolem: '问题描述',
		image: '图像',
		choosebooking: '选择预订日期',
		booking: '预订',
		alertMessage: '您确认检查了信息吗？',
		booking_success: (text: string) => `成功创建订单！ ${text}`,
	},
	InfoServicer: {
		title: '详细信息',
		all: '所有提供的服务',
		noservicer: '没有可用的服务',
		allevulate: '所有评价',
		noevulate: '没有评价',
	},
	AllReview: {
		title: '所有评价',
	},
	NotificationDetail: {
		title: '通知详情',
	},
	ChangePassword: {
		title: '修改密码',
		enterpass: '输入当前密码',
		enterpassnew: '输入新密码',
		enterpassnew1: '确认新密码',
		currentPasswordIncorrect: '当前密码错误！',
		passwordMismatch: '密码不匹配！',
		confirmChangePassword: '确定要修改密码吗？',
		changePasswordSuccess: '密码修改成功！',
		changePasswordFailure: '密码修改失败',
	},

	Setting: {
		title: '设置',
		listLanguage: ['越南语', '英语', '中文', '日语', '韩语'],
		Language: '语言',
	},
	TermsAndConditions: {
		title: '隐私政策',
		HTML: TERM.ZH,
	},
	UpdateInformation: {
		title: '更新信息',
		fullname: '姓名',
		phonenumber: '电话号码',
		addresss: '地址',
		save: '保存',
		showmessagename: '缺少姓名',
		missingPhoneNumber: '缺少电话号码',
		saveSuccess: '保存成功',
		saveFailure: '保存信息失败',
	},
	ListAddress: {
		title: '地址簿',
		addaddress: '添加地址',
		noaddress: '没有地址信息',
		name: '姓名: ',
		phone: '电话号码: ',
		address: '地址: ',
		deleteConfirm: '确定要删除吗？',
	},
	DetailOrder: {
		title: '订单详情',
		status: '状态',
		description: '描述',
		timebooking: '预约时间',
		appointmentschedule: '预约日程',
		address: '地址',
		reason: '原因',
		result: '结果',
		cancel: '取消',
		comform: '确认',
		complete: '完成',
		report: '报告',
		evulate: '评价',
		Provideslevelresults: '提供结果',
		des: '请上传结果图片以便在有问题时进行对照',
		des1: '服务与描述不符',
		other: '其他',
		cancelorder: '取消订单',
		enterdes: '输入原因',
		enterdo: '请输入原因',
		confirmSuccess: '确认成功！',
		orderCancelled: '订单已取消！',
		cancelSuccess: '取消订单成功！',
		cannotCancel: '无法取消！',
		orderInProcess: '订单已确认并正在处理中！',
		completionSuccess: '完成订单！',
		reportPrompt: '报告',
		reportDescription1: '服务与描述不符',
		reportOther: '其他',
		reportEnterDescription: '输入原因',
		reportCancel: '取消',
		reportSubmit: '完成',
	},
	AddService: {
		title: '添加服务',
		category: '服务类别',
		selectCategory: '选择服务类别',
		serviceName: '服务名称',
		image: '图片',
		uploadImage: '上传图片',
		description: '描述',
		addService: '添加',
		editService: '编辑',
		confirmCheckInfo: '您确定已经仔细检查了信息吗？',
		successMessage: '添加服务成功',
		editMessage: '编辑服务成功！',
	},
	AcceptServicer: {
		title: '批准账户',
		date: (text: string) => `注册日期: ${text}`,
	},
	Payment: {
		title: '支付',
		feeservicer: '服务费',
		payfees: '50,000越南盾/月',
		bank: '银行',
		bankname: '科技com银行',
		numberaccount: '账号',
		nameaccount: '持卡人姓名',
		descriptsion: '内容',
	},
	EvaluateService: {
		title: '评价服务',
		description: '评价内容',
		enterdescription: '请输入评价',
		image: '图片',
		evulate: '评价',
		successMessage: '评价成功',
	},
	PrivacyPolicy: {
		title: '使用条款',
		HTML: POLICY.ZH,
	},
	FAQ: {
		title: '常见问题',
		content: '以下是移动维修和维护服务应用的一些常见问题（FAQs）的示例',
		question: '问题 ',
		answer: '- 回答: ',
	},
	HomeServicer: {
		title: '订单',
		pending: '等待确认',
		inprocess: '进行中',
		completed: '已完成',
		canceled: '已取消',
	},
	Listblock: {
		title: '屏蔽列表',
		block: '屏蔽',
		enterPhoneNumber: '请输入手机号码。',
		invalidPhoneNumber: '无效的手机号码。',
		blockSuccess: '成功屏蔽手机号码！',
		confirmDelete: '您确定要删除吗？',
		deleteSuccess: '删除成功！',
	},
	OrderServicer: {
		title: '我的服务',
		servicesavailable: '您没有可用的服务',
		confirmDelete: '您确定要删除吗？',
		deleteSuccess: '删除服务成功！',
	},
	StatusOrder: {
		OrderPending: '订单等待中',
		OrderCanceled: '订单已取消',
		OrderInProcess: '订单处理中',
		OrderCompleted: '订单已完成',
	},
	AddPayment:{
		title: "THÊM PHƯƠNG THỨC THANH TOÁN",
		
	}
};
